### ISSUE TITLE
Win Condition Implementation

### ISSUE THREAD

**Issue by yauhofung** [ddesir/connect-4#11]
Deon, I believe you mentioned wanting to implement the checking for four-in-a-row.
Go ahead and fill in the `hasFourInARow()` function from our JavaScript file when you get a chance. It should be a Boolean function that returns true if the current board configuration contains a win.

**Comment by SuperArtisMickens** [comment]
After doing some research on the Internet on this matter, I found that Taylor Coon's March 2020 might be of some help.

He writes:
"
Making the auto win checker
There are a few things we need to know in order to automatically check wins. We need to know the relationship between several different slots on a line, we need to know this relationship for several different directional vectors, and, finally, we need to know the outer bounds of our matrix.
The lower bounds of our matrix is going to be any coordinate that has a y coordinate smaller than or equal to -1 or an x coordinate smaller than or equal to -1.
The upper bounds of our matrix is going to be any coordinate that has a y coordinate greater than or equal to 6 or an x coordinate greater than or equal to 7.
We know this to be true because our grid is exactly 6x7 — no smaller, no greater.
There are four different vectors where a win can take place. It can be positively diagonal, negatively diagonal, vertical, or horizontal.

Every slot on any given vertical vector will all share the same x coordinate. Therefore, traversing vertically is always going to be (x, y+1||y-1).
Every slot on any given horizontal vector will all share the same y coordinate. Therefore traversing horizontally is always going to be (x +1 || x-1, y).
Any two slots on any given diagonal vector (positive or negative) will have the same absolute value for x and y when you process the following equation:

x = x_1 - x_2
y = y_1 - y_2

Therefore, traversing diagonally is always going to be (x +||- 1, y +||- 1).
Once this is understood, all we need to do is save our landing coordinate whenever we place a token and pass it into a checker for each vector.
The way each of my checkers work is I create a loop where I extend to the edge of the board by counting up on a coordinate counter with each loop. Then, I loop back in the opposite direction by counting up on a backward-coordinate counter and subtracting it from my initial counter. As I traverse I count up on a sequence counter until I reach the end of the board again. This way, I check the entire line from the edge of the board so I won’t accidentally miss the win condition.
My sequence counter resets to 0 if it sees anything other than the current player’s identifier in sequence. If my sequence counter ever hits any number greater than or equal to 4, it breaks the loop and executes a winner’s statement.
"

You can read the whole article online:
https://medium.com/better-programming/how-to-make-connect-4-with-react-html-and-css-ec60078ca7fd 

Happy Hunting!
